language: julia
julia:
  - 0.4
  - nightly
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("GeometricalPredicates")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
